### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by bearkfear** [WesleyxBZ/calcular-jornada-trabalho#1]
Poderia colocar o intervalo, ou seja, nas jornadas de trabalho as pessoas normalmente tem um tempo para intervalo. Poderias calcular também pelo horário semanal ou mensal da pessoa ver quantas horas ela ainda precisa fazer. Poderia também definir cálculos com base no horário mensal ou semanal de quantas horas extra ela tem ou horas negativas para ela poder descontar em um prazo de N meses (talvez até discontando diretamente do tempo que ela precisa fazer ainda).

Funcionaria mais como um registro de ponto do que como uma ferramenta de calcular subtração de horários.

🚀

**Comment by WesleyxBZ** [comment]
Atualmente já é possível fazer o cálculo considerando o tempo de intervalo, é só colocar os horários de entrada e saída que mostra o total de horas realizadas no dia.
